# Site settings
title: M
name: M
description: mtsd is iOS and Ruby on Rails developer
twitter_username: mtsd
github_username: mtsd
instagram_username: matsuda

# Build settings
markdown: kramdown

# Custom
permalink: /:year/:month/:day/:title.html

#gems:
#  - jekyll-feed
#  - jekyll-gist

plugins:
  - jekyll-gist
  - jekyll-feed

# nostr
include: [".well-known"]
